import src.vdot_calculator as vdot
import datetime
from pytest import mark


@mark.parametrize(
    'v_dot, time, pace',
    [
        (30, datetime.time(hour=0, minute=8, second=30),
         datetime.time(minute=5, second=40)),
        (31, datetime.time(hour=0, minute=8, second=15),
         datetime.time(minute=5, second=30)),
        (32, datetime.time(hour=0, minute=8, second=2),
         datetime.time(minute=5, second=21)),
        (33, datetime.time(hour=0, minute=7, second=49),
         datetime.time(minute=5, second=13)),
        (34, datetime.time(hour=0, minute=7, second=37),
         datetime.time(minute=5, second=5)),
        (35, datetime.time(hour=0, minute=7, second=25),
         datetime.time(minute=4, second=57)),
        (36, datetime.time(hour=0, minute=7, second=14),
         datetime.time(minute=4, second=49)),
        (37, datetime.time(hour=0, minute=7, second=4),
         datetime.time(minute=4, second=43)),
        (38, datetime.time(hour=0, minute=6, second=54),
         datetime.time(minute=4, second=36)),
        (39, datetime.time(hour=0, minute=6, second=44),
         datetime.time(minute=4, second=29)),
        (40, datetime.time(hour=0, minute=6, second=35),
         datetime.time(minute=4, second=23)),
        (41, datetime.time(hour=0, minute=6, second=27),
         datetime.time(minute=4, second=18)),
        (42, datetime.time(hour=0, minute=6, second=19),
         datetime.time(minute=4, second=13)),
        (43, datetime.time(hour=0, minute=6, second=11),
         datetime.time(minute=4, second=7)),
        (44, datetime.time(hour=0, minute=6, second=3),
         datetime.time(minute=4, second=2)),
        (45, datetime.time(hour=0, minute=5, second=56),
         datetime.time(minute=3, second=57)),
        (46, datetime.time(hour=0, minute=5, second=49),
         datetime.time(minute=3, second=53)),
        (47, datetime.time(hour=0, minute=5, second=42),
         datetime.time(minute=3, second=48)),
        (48, datetime.time(hour=0, minute=5, second=36),
         datetime.time(minute=3, second=44)),
        (49, datetime.time(hour=0, minute=5, second=30),
         datetime.time(minute=3, second=40)),
        (50, datetime.time(hour=0, minute=5, second=24),
         datetime.time(minute=3, second=36)),
        (51, datetime.time(hour=0, minute=5, second=18),
         datetime.time(minute=3, second=32)),
        (52, datetime.time(hour=0, minute=5, second=13),
         datetime.time(minute=3, second=29)),
        (53, datetime.time(hour=0, minute=5, second=7),
         datetime.time(minute=3, second=25)),
        (54, datetime.time(hour=0, minute=5, second=2),
         datetime.time(minute=3, second=21)),
        (55, datetime.time(hour=0, minute=4, second=57),
         datetime.time(minute=3, second=18)),
        (56, datetime.time(hour=0, minute=4, second=53),
         datetime.time(minute=3, second=15)),
        (57, datetime.time(hour=0, minute=4, second=48),
         datetime.time(minute=3, second=12)),
        (58, datetime.time(hour=0, minute=4, second=44),
         datetime.time(minute=3, second=9)),
        (59, datetime.time(hour=0, minute=4, second=39),
         datetime.time(minute=3, second=6)),
        (60, datetime.time(hour=0, minute=4, second=35),
         datetime.time(minute=3, second=3)),
        (61, datetime.time(hour=0, minute=4, second=31),
         datetime.time(minute=3, second=1)),
        (62, datetime.time(hour=0, minute=4, second=27),
         datetime.time(minute=2, second=58)),
        (63, datetime.time(hour=0, minute=4, second=24),
         datetime.time(minute=2, second=56)),
        (64, datetime.time(hour=0, minute=4, second=20),
         datetime.time(minute=2, second=53)),
        (65, datetime.time(hour=0, minute=4, second=16),
         datetime.time(minute=2, second=51)),
        (66, datetime.time(hour=0, minute=4, second=13),
         datetime.time(minute=2, second=49)),
        (67, datetime.time(hour=0, minute=4, second=10),
         datetime.time(minute=2, second=47)),
        (68, datetime.time(hour=0, minute=4, second=6),
         datetime.time(minute=2, second=44)),
        (69, datetime.time(hour=0, minute=4, second=3),
         datetime.time(minute=2, second=42)),
        (70, datetime.time(hour=0, minute=4, second=0),
         datetime.time(minute=2, second=40)),
        (71, datetime.time(hour=0, minute=3, second=57),
         datetime.time(minute=2, second=38)),
        (72, datetime.time(hour=0, minute=3, second=54),
         datetime.time(minute=2, second=36)),
        (73, datetime.time(hour=0, minute=3, second=52),
         datetime.time(minute=2, second=35)),
        (74, datetime.time(hour=0, minute=3, second=49),
         datetime.time(minute=2, second=33)),
        (75, datetime.time(hour=0, minute=3, second=46),
         datetime.time(minute=2, second=31)),
        (76, datetime.time(hour=0, minute=3, second=44),
         datetime.time(minute=2, second=29)),
        (77, datetime.time(hour=0, minute=3, second=41),
         datetime.time(minute=2, second=27)),
        (78, datetime.time(hour=0, minute=3, second=39),
         datetime.time(minute=2, second=26)),
        (79, datetime.time(hour=0, minute=3, second=36),
         datetime.time(minute=2, second=24)),
        (80, datetime.time(hour=0, minute=3, second=34),
         datetime.time(minute=2, second=23)),
        (81, datetime.time(hour=0, minute=3, second=32),
         datetime.time(minute=2, second=21)),
        (82, datetime.time(hour=0, minute=3, second=30),
         datetime.time(minute=2, second=20)),
        (83, datetime.time(hour=0, minute=3, second=28),
         datetime.time(minute=2, second=18)),
        (84, datetime.time(hour=0, minute=3, second=25),
         datetime.time(minute=2, second=17)),
        (85, datetime.time(hour=0, minute=3, second=23),
         datetime.time(minute=2, second=15)),
        (30, datetime.time(hour=0, minute=9, second=11),
         datetime.time(minute=5, second=42)),
        (31, datetime.time(hour=0, minute=8, second=55),
         datetime.time(minute=5, second=32)),
        (32, datetime.time(hour=0, minute=8, second=41),
         datetime.time(minute=5, second=24)),
        (33, datetime.time(hour=0, minute=8, second=27),
         datetime.time(minute=5, second=15)),
        (34, datetime.time(hour=0, minute=8, second=14),
         datetime.time(minute=5, second=7)),
        (35, datetime.time(hour=0, minute=8, second=1),
         datetime.time(minute=4, second=59)),
        (36, datetime.time(hour=0, minute=7, second=49),
         datetime.time(minute=4, second=51)),
        (37, datetime.time(hour=0, minute=7, second=38),
         datetime.time(minute=4, second=45)),
        (38, datetime.time(hour=0, minute=7, second=27),
         datetime.time(minute=4, second=38)),
        (39, datetime.time(hour=0, minute=7, second=17),
         datetime.time(minute=4, second=32)),
        (40, datetime.time(hour=0, minute=7, second=7),
         datetime.time(minute=4, second=25)),
        (41, datetime.time(hour=0, minute=6, second=58),
         datetime.time(minute=4, second=20)),
        (42, datetime.time(hour=0, minute=6, second=49),
         datetime.time(minute=4, second=14)),
        (43, datetime.time(hour=0, minute=6, second=41),
         datetime.time(minute=4, second=9)),
        (44, datetime.time(hour=0, minute=6, second=32),
         datetime.time(minute=4, second=4)),
        (45, datetime.time(hour=0, minute=6, second=25),
         datetime.time(minute=3, second=59)),
        (46, datetime.time(hour=0, minute=6, second=17),
         datetime.time(minute=3, second=54)),
        (47, datetime.time(hour=0, minute=6, second=10),
         datetime.time(minute=3, second=50)),
        (48, datetime.time(hour=0, minute=6, second=3),
         datetime.time(minute=3, second=46)),
        (49, datetime.time(hour=0, minute=5, second=56),
         datetime.time(minute=3, second=41)),
        (50, datetime.time(hour=0, minute=5, second=50),
         datetime.time(minute=3, second=37)),
        (51, datetime.time(hour=0, minute=5, second=44),
         datetime.time(minute=3, second=34)),
        (52, datetime.time(hour=0, minute=5, second=38),
         datetime.time(minute=3, second=30)),
        (53, datetime.time(hour=0, minute=5, second=32),
         datetime.time(minute=3, second=26)),
        (54, datetime.time(hour=0, minute=5, second=27),
         datetime.time(minute=3, second=23)),
        (55, datetime.time(hour=0, minute=5, second=21),
         datetime.time(minute=3, second=19)),
        (56, datetime.time(hour=0, minute=5, second=16),
         datetime.time(minute=3, second=16)),
        (57, datetime.time(hour=0, minute=5, second=11),
         datetime.time(minute=3, second=13)),
        (58, datetime.time(hour=0, minute=5, second=6),
         datetime.time(minute=3, second=10)),
        (59, datetime.time(hour=0, minute=5, second=2),
         datetime.time(minute=3, second=8)),
        (60, datetime.time(hour=0, minute=4, second=57),
         datetime.time(minute=3, second=5)),
        (61, datetime.time(hour=0, minute=4, second=53),
         datetime.time(minute=3, second=2)),
        (62, datetime.time(hour=0, minute=4, second=49),
         datetime.time(minute=3, second=0)),
        (63, datetime.time(hour=0, minute=4, second=45),
         datetime.time(minute=2, second=57)),
        (64, datetime.time(hour=0, minute=4, second=41),
         datetime.time(minute=2, second=55)),
        (65, datetime.time(hour=0, minute=4, second=37),
         datetime.time(minute=2, second=52)),
        (66, datetime.time(hour=0, minute=4, second=33),
         datetime.time(minute=2, second=50)),
        (67, datetime.time(hour=0, minute=4, second=30),
         datetime.time(minute=2, second=48)),
        (68, datetime.time(hour=0, minute=4, second=26),
         datetime.time(minute=2, second=45)),
        (69, datetime.time(hour=0, minute=4, second=23),
         datetime.time(minute=2, second=43)),
        (70, datetime.time(hour=0, minute=4, second=19),
         datetime.time(minute=2, second=41)),
        (71, datetime.time(hour=0, minute=4, second=16),
         datetime.time(minute=2, second=39)),
        (72, datetime.time(hour=0, minute=4, second=13),
         datetime.time(minute=2, second=37)),
        (73, datetime.time(hour=0, minute=4, second=10),
         datetime.time(minute=2, second=35)),
        (74, datetime.time(hour=0, minute=4, second=7),
         datetime.time(minute=2, second=33)),
        (75, datetime.time(hour=0, minute=4, second=4),
         datetime.time(minute=2, second=32)),
        (76, datetime.time(hour=0, minute=4, second=2),
         datetime.time(minute=2, second=30)),
        (30, datetime.time(hour=0, minute=17, second=56),
         datetime.time(minute=5, second=59)),
        (31, datetime.time(hour=0, minute=17, second=27),
         datetime.time(minute=5, second=49)),
        (32, datetime.time(hour=0, minute=16, second=59),
         datetime.time(minute=5, second=40)),
        (33, datetime.time(hour=0, minute=16, second=33),
         datetime.time(minute=5, second=31)),
        (34, datetime.time(hour=0, minute=16, second=9),
         datetime.time(minute=5, second=23)),
        (35, datetime.time(hour=0, minute=15, second=45),
         datetime.time(minute=5, second=15)),
        (36, datetime.time(hour=0, minute=15, second=23),
         datetime.time(minute=5, second=8)),
        (37, datetime.time(hour=0, minute=15, second=1),
         datetime.time(minute=5, second=0)),
        (38, datetime.time(hour=0, minute=14, second=41),
         datetime.time(minute=4, second=54)),
        (39, datetime.time(hour=0, minute=14, second=21),
         datetime.time(minute=4, second=47)),
        (40, datetime.time(hour=0, minute=14, second=3),
         datetime.time(minute=4, second=41)),
        (41, datetime.time(hour=0, minute=13, second=45),
         datetime.time(minute=4, second=35)),
        (42, datetime.time(hour=0, minute=13, second=28),
         datetime.time(minute=4, second=29)),
        (43, datetime.time(hour=0, minute=13, second=11),
         datetime.time(minute=4, second=24)),
        (44, datetime.time(hour=0, minute=12, second=55),
         datetime.time(minute=4, second=18)),
        (45, datetime.time(hour=0, minute=12, second=40),
         datetime.time(minute=4, second=13)),
        (46, datetime.time(hour=0, minute=12, second=26),
         datetime.time(minute=4, second=9)),
        (47, datetime.time(hour=0, minute=12, second=12),
         datetime.time(minute=4, second=4)),
        (48, datetime.time(hour=0, minute=11, second=58),
         datetime.time(minute=3, second=59)),
        (49, datetime.time(hour=0, minute=11, second=45),
         datetime.time(minute=3, second=55)),
        (50, datetime.time(hour=0, minute=11, second=33),
         datetime.time(minute=3, second=51)),
        (51, datetime.time(hour=0, minute=11, second=21),
         datetime.time(minute=3, second=47)),
        (52, datetime.time(hour=0, minute=11, second=9),
         datetime.time(minute=3, second=43)),
        (53, datetime.time(hour=0, minute=10, second=58),
         datetime.time(minute=3, second=39)),
        (54, datetime.time(hour=0, minute=10, second=47),
         datetime.time(minute=3, second=36)),
        (55, datetime.time(hour=0, minute=10, second=37),
         datetime.time(minute=3, second=32)),
        (56, datetime.time(hour=0, minute=10, second=27),
         datetime.time(minute=3, second=29)),
        (57, datetime.time(hour=0, minute=10, second=17),
         datetime.time(minute=3, second=26)),
        (58, datetime.time(hour=0, minute=10, second=8),
         datetime.time(minute=3, second=23)),
        (59, datetime.time(hour=0, minute=9, second=58),
         datetime.time(minute=3, second=19)),
        (60, datetime.time(hour=0, minute=9, second=50),
         datetime.time(minute=3, second=17)),
        (61, datetime.time(hour=0, minute=9, second=41),
         datetime.time(minute=3, second=14)),
        (62, datetime.time(hour=0, minute=9, second=33),
         datetime.time(minute=3, second=11)),
        (63, datetime.time(hour=0, minute=9, second=25),
         datetime.time(minute=3, second=8)),
        (64, datetime.time(hour=0, minute=9, second=17),
         datetime.time(minute=3, second=6)),
        (65, datetime.time(hour=0, minute=9, second=9),
         datetime.time(minute=3, second=3)),
        (66, datetime.time(hour=0, minute=9, second=2),
         datetime.time(minute=3, second=1)),
        (67, datetime.time(hour=0, minute=8, second=55),
         datetime.time(minute=2, second=58)),
        (68, datetime.time(hour=0, minute=8, second=48),
         datetime.time(minute=2, second=56)),
        (69, datetime.time(hour=0, minute=8, second=41),
         datetime.time(minute=2, second=54)),
        (70, datetime.time(hour=0, minute=8, second=34),
         datetime.time(minute=2, second=51)),
        (71, datetime.time(hour=0, minute=8, second=28),
         datetime.time(minute=2, second=49)),
        (72, datetime.time(hour=0, minute=8, second=22),
         datetime.time(minute=2, second=47)),
        (73, datetime.time(hour=0, minute=8, second=16),
         datetime.time(minute=2, second=45)),
        (74, datetime.time(hour=0, minute=8, second=10),
         datetime.time(minute=2, second=43)),
        (75, datetime.time(hour=0, minute=8, second=4),
         datetime.time(minute=2, second=41)),
        (76, datetime.time(hour=0, minute=7, second=58),
         datetime.time(minute=2, second=39)),
        (77, datetime.time(hour=0, minute=7, second=53),
         datetime.time(minute=2, second=38)),
        (78, datetime.time(hour=0, minute=7, second=48),
         datetime.time(minute=2, second=36)),
        (79, datetime.time(hour=0, minute=7, second=43),
         datetime.time(minute=2, second=34)),
        (30, datetime.time(hour=0, minute=19, second=19),
         datetime.time(minute=6, second=0)),
        (31, datetime.time(hour=0, minute=18, second=48),
         datetime.time(minute=5, second=50)),
        (32, datetime.time(hour=0, minute=18, second=18),
         datetime.time(minute=5, second=41)),
        (33, datetime.time(hour=0, minute=17, second=50),
         datetime.time(minute=5, second=32)),
        (34, datetime.time(hour=0, minute=17, second=24),
         datetime.time(minute=5, second=24)),
        (35, datetime.time(hour=0, minute=16, second=58),
         datetime.time(minute=5, second=16)),
        (36, datetime.time(hour=0, minute=16, second=34),
         datetime.time(minute=5, second=9)),
        (37, datetime.time(hour=0, minute=16, second=11),
         datetime.time(minute=5, second=2)),
        (38, datetime.time(hour=0, minute=15, second=49),
         datetime.time(minute=4, second=55)),
        (39, datetime.time(hour=0, minute=15, second=29),
         datetime.time(minute=4, second=49)),
        (40, datetime.time(hour=0, minute=15, second=8),
         datetime.time(minute=4, second=42)),
        (41, datetime.time(hour=0, minute=14, second=49),
         datetime.time(minute=4, second=36)),
        (42, datetime.time(hour=0, minute=14, second=31),
         datetime.time(minute=4, second=31)),
        (43, datetime.time(hour=0, minute=14, second=13),
         datetime.time(minute=4, second=25)),
        (44, datetime.time(hour=0, minute=13, second=56),
         datetime.time(minute=4, second=20)),
        (45, datetime.time(hour=0, minute=13, second=40),
         datetime.time(minute=4, second=15)),
        (46, datetime.time(hour=0, minute=13, second=25),
         datetime.time(minute=4, second=10)),
        (47, datetime.time(hour=0, minute=13, second=10),
         datetime.time(minute=4, second=5)),
        (48, datetime.time(hour=0, minute=12, second=55),
         datetime.time(minute=4, second=1)),
        (49, datetime.time(hour=0, minute=12, second=41),
         datetime.time(minute=3, second=56)),
        (50, datetime.time(hour=0, minute=12, second=28),
         datetime.time(minute=3, second=52)),
        (51, datetime.time(hour=0, minute=12, second=15),
         datetime.time(minute=3, second=48)),
        (52, datetime.time(hour=0, minute=12, second=2),
         datetime.time(minute=3, second=44)),
        (53, datetime.time(hour=0, minute=11, second=50),
         datetime.time(minute=3, second=41)),
        (54, datetime.time(hour=0, minute=11, second=39),
         datetime.time(minute=3, second=37)),
        (55, datetime.time(hour=0, minute=11, second=28),
         datetime.time(minute=3, second=34)),
        (56, datetime.time(hour=0, minute=11, second=17),
         datetime.time(minute=3, second=30)),
        (57, datetime.time(hour=0, minute=11, second=6),
         datetime.time(minute=3, second=27)),
        (58, datetime.time(hour=0, minute=10, second=56),
         datetime.time(minute=3, second=24)),
        (59, datetime.time(hour=0, minute=10, second=46),
         datetime.time(minute=3, second=21)),
        (60, datetime.time(hour=0, minute=10, second=37),
         datetime.time(minute=3, second=18)),
        (61, datetime.time(hour=0, minute=10, second=27),
         datetime.time(minute=3, second=15)),
        (62, datetime.time(hour=0, minute=10, second=18),
         datetime.time(minute=3, second=12)),
        (63, datetime.time(hour=0, minute=10, second=10),
         datetime.time(minute=3, second=10)),
        (64, datetime.time(hour=0, minute=10, second=1),
         datetime.time(minute=3, second=7)),
        (65, datetime.time(hour=0, minute=9, second=53),
         datetime.time(minute=3, second=4)),
        (66, datetime.time(hour=0, minute=9, second=45),
         datetime.time(minute=3, second=2)),
        (67, datetime.time(hour=0, minute=9, second=37),
         datetime.time(minute=2, second=59)),
        (68, datetime.time(hour=0, minute=9, second=30),
         datetime.time(minute=2, second=57)),
        (69, datetime.time(hour=0, minute=9, second=23),
         datetime.time(minute=2, second=55)),
        (70, datetime.time(hour=0, minute=9, second=16),
         datetime.time(minute=2, second=53)),
        (71, datetime.time(hour=0, minute=9, second=9),
         datetime.time(minute=2, second=51)),
        (72, datetime.time(hour=0, minute=9, second=2),
         datetime.time(minute=2, second=48)),
        (73, datetime.time(hour=0, minute=8, second=55),
         datetime.time(minute=2, second=46)),
        (74, datetime.time(hour=0, minute=8, second=49),
         datetime.time(minute=2, second=44)),
        (75, datetime.time(hour=0, minute=8, second=43),
         datetime.time(minute=2, second=42)),
        (76, datetime.time(hour=0, minute=8, second=37),
         datetime.time(minute=2, second=41)),
        (77, datetime.time(hour=0, minute=8, second=31),
         datetime.time(minute=2, second=39)),
        (78, datetime.time(hour=0, minute=8, second=25),
         datetime.time(minute=2, second=37)),
        (79, datetime.time(hour=0, minute=8, second=20),
         datetime.time(minute=2, second=35)),
        (30, datetime.time(hour=0, minute=30, second=40),
         datetime.time(minute=6, second=8)),
        (31, datetime.time(hour=0, minute=29, second=51),
         datetime.time(minute=5, second=58)),
        (32, datetime.time(hour=0, minute=29, second=5),
         datetime.time(minute=5, second=49)),
        (33, datetime.time(hour=0, minute=28, second=21),
         datetime.time(minute=5, second=40)),
        (34, datetime.time(hour=0, minute=27, second=39),
         datetime.time(minute=5, second=32)),
        (35, datetime.time(hour=0, minute=27, second=0),
         datetime.time(minute=5, second=24)),
        (36, datetime.time(hour=0, minute=26, second=22),
         datetime.time(minute=5, second=16)),
        (37, datetime.time(hour=0, minute=25, second=46),
         datetime.time(minute=5, second=9)),
        (38, datetime.time(hour=0, minute=25, second=12),
         datetime.time(minute=5, second=2)),
        (39, datetime.time(hour=0, minute=24, second=39),
         datetime.time(minute=4, second=56)),
        (40, datetime.time(hour=0, minute=24, second=8),
         datetime.time(minute=4, second=50)),
        (41, datetime.time(hour=0, minute=23, second=38),
         datetime.time(minute=4, second=44)),
        (42, datetime.time(hour=0, minute=23, second=9),
         datetime.time(minute=4, second=38)),
        (43, datetime.time(hour=0, minute=22, second=41),
         datetime.time(minute=4, second=32)),
        (44, datetime.time(hour=0, minute=22, second=15),
         datetime.time(minute=4, second=27)),
        (45, datetime.time(hour=0, minute=21, second=50),
         datetime.time(minute=4, second=22)),
        (46, datetime.time(hour=0, minute=21, second=25),
         datetime.time(minute=4, second=17)),
        (47, datetime.time(hour=0, minute=21, second=2),
         datetime.time(minute=4, second=12)),
        (48, datetime.time(hour=0, minute=20, second=39),
         datetime.time(minute=4, second=8)),
        (49, datetime.time(hour=0, minute=20, second=18),
         datetime.time(minute=4, second=4)),
        (50, datetime.time(hour=0, minute=19, second=57),
         datetime.time(minute=3, second=59)),
        (51, datetime.time(hour=0, minute=19, second=36),
         datetime.time(minute=3, second=55)),
        (52, datetime.time(hour=0, minute=19, second=17),
         datetime.time(minute=3, second=51)),
        (53, datetime.time(hour=0, minute=18, second=58),
         datetime.time(minute=3, second=48)),
        (54, datetime.time(hour=0, minute=18, second=40),
         datetime.time(minute=3, second=44)),
        (55, datetime.time(hour=0, minute=18, second=22),
         datetime.time(minute=3, second=40)),
        (56, datetime.time(hour=0, minute=18, second=5),
         datetime.time(minute=3, second=37)),
        (57, datetime.time(hour=0, minute=17, second=49),
         datetime.time(minute=3, second=34)),
        (58, datetime.time(hour=0, minute=17, second=33),
         datetime.time(minute=3, second=31)),
        (59, datetime.time(hour=0, minute=17, second=17),
         datetime.time(minute=3, second=27)),
        (60, datetime.time(hour=0, minute=17, second=3),
         datetime.time(minute=3, second=25)),
        (61, datetime.time(hour=0, minute=16, second=48),
         datetime.time(minute=3, second=22)),
        (62, datetime.time(hour=0, minute=16, second=34),
         datetime.time(minute=3, second=19)),
        (63, datetime.time(hour=0, minute=16, second=20),
         datetime.time(minute=3, second=16)),
        (64, datetime.time(hour=0, minute=16, second=7),
         datetime.time(minute=3, second=13)),
        (65, datetime.time(hour=0, minute=15, second=54),
         datetime.time(minute=3, second=11)),
        (66, datetime.time(hour=0, minute=15, second=42),
         datetime.time(minute=3, second=8)),
        (67, datetime.time(hour=0, minute=15, second=29),
         datetime.time(minute=3, second=6)),
        (68, datetime.time(hour=0, minute=15, second=18),
         datetime.time(minute=3, second=4)),
        (69, datetime.time(hour=0, minute=15, second=6),
         datetime.time(minute=3, second=1)),
        (70, datetime.time(hour=0, minute=14, second=55),
         datetime.time(minute=2, second=59)),
        (71, datetime.time(hour=0, minute=14, second=44),
         datetime.time(minute=2, second=57)),
        (72, datetime.time(hour=0, minute=14, second=33),
         datetime.time(minute=2, second=55)),
        (73, datetime.time(hour=0, minute=14, second=23),
         datetime.time(minute=2, second=53)),
        (74, datetime.time(hour=0, minute=14, second=13),
         datetime.time(minute=2, second=51)),
        (75, datetime.time(hour=0, minute=14, second=3),
         datetime.time(minute=2, second=49)),
        (76, datetime.time(hour=0, minute=13, second=54),
         datetime.time(minute=2, second=47)),
        (77, datetime.time(hour=0, minute=13, second=44),
         datetime.time(minute=2, second=45)),
        (78, datetime.time(hour=0, minute=13, second=35),
         datetime.time(minute=2, second=43)),
        (79, datetime.time(hour=0, minute=13, second=26),
         datetime.time(minute=2, second=41)),
        (30, datetime.time(hour=1, minute=3, second=46),
         datetime.time(minute=6, second=23)),
        (31, datetime.time(hour=1, minute=2, second=3),
         datetime.time(minute=6, second=12)),
        (32, datetime.time(hour=1, minute=0, second=26),
         datetime.time(minute=6, second=3)),
        (33, datetime.time(hour=0, minute=58, second=54),
         datetime.time(minute=5, second=53)),
        (34, datetime.time(hour=0, minute=57, second=26),
         datetime.time(minute=5, second=45)),
        (35, datetime.time(hour=0, minute=56, second=3),
         datetime.time(minute=5, second=36)),
        (36, datetime.time(hour=0, minute=54, second=44),
         datetime.time(minute=5, second=28)),
        (37, datetime.time(hour=0, minute=53, second=29),
         datetime.time(minute=5, second=21)),
        (38, datetime.time(hour=0, minute=52, second=17),
         datetime.time(minute=5, second=14)),
        (39, datetime.time(hour=0, minute=51, second=9),
         datetime.time(minute=5, second=7)),
        (40, datetime.time(hour=0, minute=50, second=3),
         datetime.time(minute=5, second=0)),
        (41, datetime.time(hour=0, minute=49, second=1),
         datetime.time(minute=4, second=54)),
        (42, datetime.time(hour=0, minute=48, second=1),
         datetime.time(minute=4, second=48)),
        (43, datetime.time(hour=0, minute=47, second=4),
         datetime.time(minute=4, second=42)),
        (44, datetime.time(hour=0, minute=46, second=9),
         datetime.time(minute=4, second=37)),
        (45, datetime.time(hour=0, minute=45, second=16),
         datetime.time(minute=4, second=32)),
        (46, datetime.time(hour=0, minute=44, second=25),
         datetime.time(minute=4, second=26)),
        (47, datetime.time(hour=0, minute=43, second=36),
         datetime.time(minute=4, second=22)),
        (48, datetime.time(hour=0, minute=42, second=50),
         datetime.time(minute=4, second=17)),
        (49, datetime.time(hour=0, minute=42, second=4),
         datetime.time(minute=4, second=12)),
        (50, datetime.time(hour=0, minute=41, second=21),
         datetime.time(minute=4, second=8)),
        (51, datetime.time(hour=0, minute=40, second=39),
         datetime.time(minute=4, second=4)),
        (52, datetime.time(hour=0, minute=39, second=59),
         datetime.time(minute=4, second=0)),
        (53, datetime.time(hour=0, minute=39, second=20),
         datetime.time(minute=3, second=56)),
        (54, datetime.time(hour=0, minute=38, second=42),
         datetime.time(minute=3, second=52)),
        (55, datetime.time(hour=0, minute=38, second=6),
         datetime.time(minute=3, second=49)),
        (56, datetime.time(hour=0, minute=37, second=31),
         datetime.time(minute=3, second=45)),
        (57, datetime.time(hour=0, minute=36, second=57),
         datetime.time(minute=3, second=42)),
        (58, datetime.time(hour=0, minute=36, second=24),
         datetime.time(minute=3, second=38)),
        (59, datetime.time(hour=0, minute=35, second=52),
         datetime.time(minute=3, second=35)),
        (60, datetime.time(hour=0, minute=35, second=22),
         datetime.time(minute=3, second=32)),
        (61, datetime.time(hour=0, minute=34, second=52),
         datetime.time(minute=3, second=29)),
        (62, datetime.time(hour=0, minute=34, second=23),
         datetime.time(minute=3, second=26)),
        (63, datetime.time(hour=0, minute=33, second=55),
         datetime.time(minute=3, second=24)),
        (64, datetime.time(hour=0, minute=33, second=28),
         datetime.time(minute=3, second=21)),
        (65, datetime.time(hour=0, minute=33, second=1),
         datetime.time(minute=3, second=18)),
        (66, datetime.time(hour=0, minute=32, second=35),
         datetime.time(minute=3, second=16)),
        (67, datetime.time(hour=0, minute=32, second=11),
         datetime.time(minute=3, second=13)),
        (68, datetime.time(hour=0, minute=31, second=46),
         datetime.time(minute=3, second=11)),
        (69, datetime.time(hour=0, minute=31, second=23),
         datetime.time(minute=3, second=8)),
        (70, datetime.time(hour=0, minute=31, second=0),
         datetime.time(minute=3, second=6)),
        (71, datetime.time(hour=0, minute=30, second=38),
         datetime.time(minute=3, second=4)),
        (72, datetime.time(hour=0, minute=30, second=16),
         datetime.time(minute=3, second=2)),
        (73, datetime.time(hour=0, minute=29, second=55),
         datetime.time(minute=3, second=0)),
        (74, datetime.time(hour=0, minute=29, second=34),
         datetime.time(minute=2, second=57)),
        (75, datetime.time(hour=0, minute=29, second=14),
         datetime.time(minute=2, second=55)),
        (76, datetime.time(hour=0, minute=28, second=55),
         datetime.time(minute=2, second=54)),
        (77, datetime.time(hour=0, minute=28, second=36),
         datetime.time(minute=2, second=52)),
        (78, datetime.time(hour=0, minute=28, second=17),
         datetime.time(minute=2, second=50)),
        (79, datetime.time(hour=0, minute=27, second=59),
         datetime.time(minute=2, second=48)),
        (81, datetime.time(hour=0, minute=27, second=24),
         datetime.time(minute=2, second=44)),
        (82, datetime.time(hour=0, minute=27, second=7),
         datetime.time(minute=2, second=43)),
        (83, datetime.time(hour=0, minute=26, second=51),
         datetime.time(minute=2, second=41)),
        (84, datetime.time(hour=0, minute=26, second=34),
         datetime.time(minute=2, second=39)),
        (85, datetime.time(hour=0, minute=26, second=19),
         datetime.time(minute=2, second=38)),
        (30, datetime.time(hour=1, minute=38, second=14),
         datetime.time(minute=6, second=33)),
        (31, datetime.time(hour=1, minute=35, second=36),
         datetime.time(minute=6, second=22)),
        (32, datetime.time(hour=1, minute=33, second=7),
         datetime.time(minute=6, second=12)),
        (33, datetime.time(hour=1, minute=30, second=45),
         datetime.time(minute=6, second=3)),
        (34, datetime.time(hour=1, minute=28, second=30),
         datetime.time(minute=5, second=54)),
        (35, datetime.time(hour=1, minute=26, second=22),
         datetime.time(minute=5, second=45)),
        (36, datetime.time(hour=1, minute=24, second=20),
         datetime.time(minute=5, second=37)),
        (37, datetime.time(hour=1, minute=22, second=24),
         datetime.time(minute=5, second=30)),
        (38, datetime.time(hour=1, minute=20, second=33),
         datetime.time(minute=5, second=22)),
        (39, datetime.time(hour=1, minute=18, second=47),
         datetime.time(minute=5, second=15)),
        (40, datetime.time(hour=1, minute=17, second=6),
         datetime.time(minute=5, second=8)),
        (41, datetime.time(hour=1, minute=15, second=29),
         datetime.time(minute=5, second=2)),
        (42, datetime.time(hour=1, minute=13, second=56),
         datetime.time(minute=4, second=56)),
        (43, datetime.time(hour=1, minute=12, second=27),
         datetime.time(minute=4, second=50)),
        (44, datetime.time(hour=1, minute=11, second=2),
         datetime.time(minute=4, second=44)),
        (45, datetime.time(hour=1, minute=9, second=40),
         datetime.time(minute=4, second=39)),
        (46, datetime.time(hour=1, minute=8, second=22),
         datetime.time(minute=4, second=33)),
        (47, datetime.time(hour=1, minute=7, second=6),
         datetime.time(minute=4, second=28)),
        (48, datetime.time(hour=1, minute=5, second=53),
         datetime.time(minute=4, second=24)),
        (49, datetime.time(hour=1, minute=4, second=44),
         datetime.time(minute=4, second=19)),
        (50, datetime.time(hour=1, minute=3, second=36),
         datetime.time(minute=4, second=14)),
        (51, datetime.time(hour=1, minute=2, second=31),
         datetime.time(minute=4, second=10)),
        (52, datetime.time(hour=1, minute=1, second=29),
         datetime.time(minute=4, second=6)),
        (53, datetime.time(hour=1, minute=0, second=28),
         datetime.time(minute=4, second=2)),
        (54, datetime.time(hour=0, minute=59, second=30),
         datetime.time(minute=3, second=58)),
        (55, datetime.time(hour=0, minute=58, second=33),
         datetime.time(minute=3, second=54)),
        (56, datetime.time(hour=0, minute=57, second=39),
         datetime.time(minute=3, second=51)),
        (57, datetime.time(hour=0, minute=56, second=46),
         datetime.time(minute=3, second=47)),
        (58, datetime.time(hour=0, minute=55, second=55),
         datetime.time(minute=3, second=44)),
        (59, datetime.time(hour=0, minute=55, second=6),
         datetime.time(minute=3, second=40)),
        (60, datetime.time(hour=0, minute=54, second=18),
         datetime.time(minute=3, second=37)),
        (61, datetime.time(hour=0, minute=53, second=32),
         datetime.time(minute=3, second=34)),
        (62, datetime.time(hour=0, minute=52, second=47),
         datetime.time(minute=3, second=31)),
        (63, datetime.time(hour=0, minute=52, second=3),
         datetime.time(minute=3, second=28)),
        (64, datetime.time(hour=0, minute=51, second=21),
         datetime.time(minute=3, second=25)),
        (65, datetime.time(hour=0, minute=50, second=40),
         datetime.time(minute=3, second=23)),
        (66, datetime.time(hour=0, minute=50, second=0),
         datetime.time(minute=3, second=20)),
        (67, datetime.time(hour=0, minute=49, second=22),
         datetime.time(minute=3, second=17)),
        (68, datetime.time(hour=0, minute=48, second=44),
         datetime.time(minute=3, second=15)),
        (69, datetime.time(hour=0, minute=48, second=8),
         datetime.time(minute=3, second=13)),
        (70, datetime.time(hour=0, minute=47, second=32),
         datetime.time(minute=3, second=10)),
        (71, datetime.time(hour=0, minute=46, second=58),
         datetime.time(minute=3, second=8)),
        (72, datetime.time(hour=0, minute=46, second=24),
         datetime.time(minute=3, second=6)),
        (73, datetime.time(hour=0, minute=45, second=51),
         datetime.time(minute=3, second=3)),
        (74, datetime.time(hour=0, minute=45, second=19),
         datetime.time(minute=3, second=1)),
        (75, datetime.time(hour=0, minute=44, second=48),
         datetime.time(minute=2, second=59)),
        (76, datetime.time(hour=0, minute=44, second=18),
         datetime.time(minute=2, second=57)),
        (77, datetime.time(hour=0, minute=43, second=49),
         datetime.time(minute=2, second=55)),
        (78, datetime.time(hour=0, minute=43, second=20),
         datetime.time(minute=2, second=53)),
        (79, datetime.time(hour=0, minute=42, second=52),
         datetime.time(minute=2, second=51)),
        (80, datetime.time(hour=0, minute=42, second=25),
         datetime.time(minute=2, second=50)),
        (81, datetime.time(hour=0, minute=41, second=58),
         datetime.time(minute=2, second=48)),
        (82, datetime.time(hour=0, minute=41, second=32),
         datetime.time(minute=2, second=46)),
        (83, datetime.time(hour=0, minute=41, second=6),
         datetime.time(minute=2, second=44)),
        (84, datetime.time(hour=0, minute=40, second=42),
         datetime.time(minute=2, second=43)),
        (85, datetime.time(hour=0, minute=40, second=17),
         datetime.time(minute=2, second=41)),
        (30, datetime.time(hour=2, minute=21, second=4),
         datetime.time(minute=6, second=41)),
        (31, datetime.time(hour=2, minute=17, second=21),
         datetime.time(minute=6, second=31)),
        (32, datetime.time(hour=2, minute=13, second=49),
         datetime.time(minute=6, second=21)),
        (33, datetime.time(hour=2, minute=10, second=27),
         datetime.time(minute=6, second=11)),
        (34, datetime.time(hour=2, minute=7, second=16),
         datetime.time(minute=6, second=2)),
        (35, datetime.time(hour=2, minute=4, second=13),
         datetime.time(minute=5, second=53)),
        (36, datetime.time(hour=2, minute=1, second=19),
         datetime.time(minute=5, second=45)),
        (37, datetime.time(hour=1, minute=58, second=34),
         datetime.time(minute=5, second=37)),
        (38, datetime.time(hour=1, minute=55, second=55),
         datetime.time(minute=5, second=30)),
        (39, datetime.time(hour=1, minute=53, second=24),
         datetime.time(minute=5, second=23)),
        (40, datetime.time(hour=1, minute=50, second=59),
         datetime.time(minute=5, second=16)),
        (41, datetime.time(hour=1, minute=48, second=40),
         datetime.time(minute=5, second=9)),
        (42, datetime.time(hour=1, minute=46, second=27),
         datetime.time(minute=5, second=3)),
        (43, datetime.time(hour=1, minute=44, second=20),
         datetime.time(minute=4, second=57)),
        (44, datetime.time(hour=1, minute=42, second=17),
         datetime.time(minute=4, second=51)),
        (45, datetime.time(hour=1, minute=40, second=20),
         datetime.time(minute=4, second=45)),
        (46, datetime.time(hour=1, minute=38, second=27),
         datetime.time(minute=4, second=40)),
        (47, datetime.time(hour=1, minute=36, second=38),
         datetime.time(minute=4, second=35)),
        (48, datetime.time(hour=1, minute=34, second=53),
         datetime.time(minute=4, second=30)),
        (49, datetime.time(hour=1, minute=33, second=12),
         datetime.time(minute=4, second=25)),
        (50, datetime.time(hour=1, minute=31, second=35),
         datetime.time(minute=4, second=20)),
        (51, datetime.time(hour=1, minute=30, second=2),
         datetime.time(minute=4, second=16)),
        (52, datetime.time(hour=1, minute=28, second=31),
         datetime.time(minute=4, second=12)),
        (53, datetime.time(hour=1, minute=27, second=4),
         datetime.time(minute=4, second=8)),
        (54, datetime.time(hour=1, minute=25, second=40),
         datetime.time(minute=4, second=4)),
        (55, datetime.time(hour=1, minute=24, second=18),
         datetime.time(minute=4, second=0)),
        (56, datetime.time(hour=1, minute=23, second=0),
         datetime.time(minute=3, second=56)),
        (57, datetime.time(hour=1, minute=21, second=43),
         datetime.time(minute=3, second=52)),
        (58, datetime.time(hour=1, minute=20, second=30),
         datetime.time(minute=3, second=49)),
        (59, datetime.time(hour=1, minute=19, second=18),
         datetime.time(minute=3, second=46)),
        (60, datetime.time(hour=1, minute=18, second=9),
         datetime.time(minute=3, second=42)),
        (61, datetime.time(hour=1, minute=17, second=2),
         datetime.time(minute=3, second=39)),
        (62, datetime.time(hour=1, minute=15, second=57),
         datetime.time(minute=3, second=36)),
        (63, datetime.time(hour=1, minute=14, second=54),
         datetime.time(minute=3, second=33)),
        (64, datetime.time(hour=1, minute=13, second=53),
         datetime.time(minute=3, second=30)),
        (65, datetime.time(hour=1, minute=12, second=53),
         datetime.time(minute=3, second=27)),
        (66, datetime.time(hour=1, minute=11, second=56),
         datetime.time(minute=3, second=25)),
        (67, datetime.time(hour=1, minute=11, second=0),
         datetime.time(minute=3, second=22)),
        (68, datetime.time(hour=1, minute=10, second=5),
         datetime.time(minute=3, second=19)),
        (69, datetime.time(hour=1, minute=9, second=12),
         datetime.time(minute=3, second=17)),
        (70, datetime.time(hour=1, minute=8, second=21),
         datetime.time(minute=3, second=14)),
        (71, datetime.time(hour=1, minute=7, second=31),
         datetime.time(minute=3, second=12)),
        (72, datetime.time(hour=1, minute=6, second=42),
         datetime.time(minute=3, second=10)),
        (73, datetime.time(hour=1, minute=5, second=54),
         datetime.time(minute=3, second=7)),
        (74, datetime.time(hour=1, minute=5, second=8),
         datetime.time(minute=3, second=5)),
        (75, datetime.time(hour=1, minute=4, second=23),
         datetime.time(minute=3, second=3)),
        (76, datetime.time(hour=1, minute=3, second=39),
         datetime.time(minute=3, second=1)),
        (77, datetime.time(hour=1, minute=2, second=56),
         datetime.time(minute=2, second=59)),
        (78, datetime.time(hour=1, minute=2, second=15),
         datetime.time(minute=2, second=57)),
        (79, datetime.time(hour=1, minute=1, second=34),
         datetime.time(minute=2, second=55)),
        (80, datetime.time(hour=1, minute=0, second=54),
         datetime.time(minute=2, second=53)),
        (81, datetime.time(hour=1, minute=0, second=15),
         datetime.time(minute=2, second=51)),
        (82, datetime.time(hour=0, minute=59, second=38),
         datetime.time(minute=2, second=50)),
        (83, datetime.time(hour=0, minute=59, second=1),
         datetime.time(minute=2, second=48)),
        (84, datetime.time(hour=0, minute=58, second=25),
         datetime.time(minute=2, second=46)),
        (85, datetime.time(hour=0, minute=57, second=50),
         datetime.time(minute=2, second=44)),
        (30, datetime.time(hour=4, minute=49, second=17),
         datetime.time(minute=6, second=51)),
        (31, datetime.time(hour=4, minute=41, second=57),
         datetime.time(minute=6, second=41)),
        (32, datetime.time(hour=4, minute=34, second=59),
         datetime.time(minute=6, second=31)),
        (33, datetime.time(hour=4, minute=28, second=22),
         datetime.time(minute=6, second=22)),
        (34, datetime.time(hour=4, minute=22, second=3),
         datetime.time(minute=6, second=13)),
        (35, datetime.time(hour=4, minute=16, second=3),
         datetime.time(minute=6, second=4)),
        (36, datetime.time(hour=4, minute=10, second=19),
         datetime.time(minute=5, second=56)),
        (37, datetime.time(hour=4, minute=4, second=50),
         datetime.time(minute=5, second=48)),
        (38, datetime.time(hour=3, minute=59, second=35),
         datetime.time(minute=5, second=41)),
        (39, datetime.time(hour=3, minute=54, second=34),
         datetime.time(minute=5, second=34)),
        (40, datetime.time(hour=3, minute=49, second=45),
         datetime.time(minute=5, second=27)),
        (41, datetime.time(hour=3, minute=45, second=9),
         datetime.time(minute=5, second=20)),
        (42, datetime.time(hour=3, minute=40, second=43),
         datetime.time(minute=5, second=14)),
        (43, datetime.time(hour=3, minute=36, second=28),
         datetime.time(minute=5, second=8)),
        (44, datetime.time(hour=3, minute=32, second=23),
         datetime.time(minute=5, second=2)),
        (45, datetime.time(hour=3, minute=28, second=26),
         datetime.time(minute=4, second=56)),
        (46, datetime.time(hour=3, minute=24, second=39),
         datetime.time(minute=4, second=51)),
        (47, datetime.time(hour=3, minute=21, second=0),
         datetime.time(minute=4, second=46)),
        (48, datetime.time(hour=3, minute=17, second=29),
         datetime.time(minute=4, second=41)),
        (49, datetime.time(hour=3, minute=14, second=6),
         datetime.time(minute=4, second=36)),
        (50, datetime.time(hour=3, minute=10, second=49),
         datetime.time(minute=4, second=31)),
        (51, datetime.time(hour=3, minute=7, second=39),
         datetime.time(minute=4, second=27)),
        (52, datetime.time(hour=3, minute=4, second=36),
         datetime.time(minute=4, second=22)),
        (53, datetime.time(hour=3, minute=1, second=39),
         datetime.time(minute=4, second=18)),
        (54, datetime.time(hour=2, minute=58, second=47),
         datetime.time(minute=4, second=14)),
        (55, datetime.time(hour=2, minute=56, second=1),
         datetime.time(minute=4, second=10)),
        (56, datetime.time(hour=2, minute=53, second=20),
         datetime.time(minute=4, second=6)),
        (57, datetime.time(hour=2, minute=50, second=45),
         datetime.time(minute=4, second=3)),
        (58, datetime.time(hour=2, minute=48, second=14),
         datetime.time(minute=3, second=59)),
        (59, datetime.time(hour=2, minute=45, second=47),
         datetime.time(minute=3, second=56)),
        (60, datetime.time(hour=2, minute=43, second=25),
         datetime.time(minute=3, second=52)),
        (61, datetime.time(hour=2, minute=41, second=8),
         datetime.time(minute=3, second=49)),
        (62, datetime.time(hour=2, minute=38, second=54),
         datetime.time(minute=3, second=46)),
        (63, datetime.time(hour=2, minute=36, second=44),
         datetime.time(minute=3, second=43)),
        (64, datetime.time(hour=2, minute=34, second=38),
         datetime.time(minute=3, second=40)),
        (65, datetime.time(hour=2, minute=32, second=35),
         datetime.time(minute=3, second=37)),
        (66, datetime.time(hour=2, minute=30, second=36),
         datetime.time(minute=3, second=34)),
        (67, datetime.time(hour=2, minute=28, second=40),
         datetime.time(minute=3, second=31)),
        (68, datetime.time(hour=2, minute=26, second=47),
         datetime.time(minute=3, second=29)),
        (69, datetime.time(hour=2, minute=24, second=57),
         datetime.time(minute=3, second=26)),
        (70, datetime.time(hour=2, minute=23, second=10),
         datetime.time(minute=3, second=24)),
        (71, datetime.time(hour=2, minute=21, second=26),
         datetime.time(minute=3, second=21)),
        (72, datetime.time(hour=2, minute=19, second=44),
         datetime.time(minute=3, second=19)),
        (73, datetime.time(hour=2, minute=18, second=5),
         datetime.time(minute=3, second=16)),
        (74, datetime.time(hour=2, minute=16, second=29),
         datetime.time(minute=3, second=14)),
        (75, datetime.time(hour=2, minute=14, second=55),
         datetime.time(minute=3, second=12)),
        (76, datetime.time(hour=2, minute=13, second=23),
         datetime.time(minute=3, second=10)),
        (77, datetime.time(hour=2, minute=11, second=54),
         datetime.time(minute=3, second=8)),
        (78, datetime.time(hour=2, minute=10, second=27),
         datetime.time(minute=3, second=5)),
        (79, datetime.time(hour=2, minute=9, second=2),
         datetime.time(minute=3, second=3)),
        (80, datetime.time(hour=2, minute=7, second=38),
         datetime.time(minute=3, second=1)),
        (81, datetime.time(hour=2, minute=6, second=17),
         datetime.time(minute=3, second=0)),
        (82, datetime.time(hour=2, minute=4, second=57),
         datetime.time(minute=2, second=58)),
        (83, datetime.time(hour=2, minute=3, second=40),
         datetime.time(minute=2, second=56)),
        (84, datetime.time(hour=2, minute=2, second=24),
         datetime.time(minute=2, second=54)),
        (85, datetime.time(hour=2, minute=1, second=10),
         datetime.time(minute=2, second=52)),
    ],
)
def test_vdot_from_time_and_pace(v_dot, time, pace):
    error = vdot.vdot_from_time_and_pace(time, pace) - v_dot
    assert abs(error) <= 0.35